# using old infrastructure
language: python
python:
- '2.7'
sudo: required
before_install:
- sudo apt-get install -y python-lxml libxml2-dev libxslt1-dev git tidy wget
- pip install --use-mirrors pillow cssutils lxml docutils roman
- pip install --use-mirrors future requests
- wget http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz
- tar xvfz kindlegen_linux_2.6_i386_v2_9.tar.gz
- sudo ln -s /kindlegen /usr/local/bin/kindlegen
install:
- pip install git+git://github.com/rdhyee/pg-epubmaker.git
before_script:
- export PATH=$PATH:/usr/local/bin
script:
- python test.py
- epubmaker --ebook=2701 --title="Moby Dick" --make=all  2701-h.htm
branches:
  only:
  - master
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: rJMy48tisRU1aRw7R/0ic0iJsb6AQO3BkfV3ADQhrO259g0gVBB7GSA8oje3xvQ/vdnQ0Kc2SAUu2hrK3/9e/oXJbSrVisUM9ycg8MqWs36zxFzOS3O/fzYMlAmPSwNGp08U4kzKj9VpjNz9GdFDW4NWC9DZzaX0gvp4OlOO+gRkT3CWczzugwKdKMlkg0TKS97hCvd3Jn6urUPlAS4tLEdaXDfbfww2QwDXwfLW/wxC8kQAVgObPy/4fivu5rwwtPxylM3+ahZS82mq9ddXpROmpXb7/S9DCyTpH+3Fvec4jzWFKHshfJy+jLmToZVryBjNWKN46CHIL1PuheU6GTM0gbzzv4X1rTsLA3/B9JDhKsz9L2i2UFSBVthckwVwACKe5KIT0EOu63KLmxs3BmeHauwvgErQvhsqcKNAD34CcjnhECpZHqsHgbkvUWJ9G2rNG/6Dj8qDMyhdlhxmmK5us6fG+OulNHs2egyXX4OpfhPk1lMzb2Yk1Q2PSKk3ycb/ZLKDeBXo0urVzfU2CneA6oz6iUjEMz+Z3hdYs/KFZjXHVBjAUGYB2ef6DcoL93WccOX8jl0N3qotIK5IMNbxJzP/zw46ZvbzDDm+knONlE/MnUNMlSGdC3j6e4eVlUw/HpiL44WVwHkSEkAXIH/0mXyr7F3Pt/S/aFt2uD8=
  file: 2701-epub.epub
  on:
    repo: rdhyee/epubmaker-docker-travis
